SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Game states
MENU = 0
GAME = 1

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds between shots

# Powerup constants
POWERUP_RADIUS = 15
POWERUP_SPAWN_RATE = 15.0  # seconds
POWERUP_SPEED = 150
POWERUP_DURATION = 10.0  # seconds
POWERUP_SHOT_MULTIPLIER = 10  # Shot speed multiplier